<div class="col py-3 px-4 border bg-light">
    <a href="<?= $this->url('game', ['id' => $game['id']]) ?>">
        <img src="<?= $this->escapeHtml($game['thumbnail']) ?>" class="img-fluid rounded">
    </a>
    <a href="<?= $this->escapeHtml($game['game_url']) ?>" target="_blank">
        <h5 class="d-none d-md-block">
            <?= $this->escapeHtml($game['title']) ?>
        </h5>
    </a>
</div>
