<?php
/**
 * @var string $title
 * @var \Laminas\Form\Form $form
 * @var array $games
 */
?>

<div class="row justify-content-between align-items-center pb-3 px-4">
    <div class="">
        <h1><?= $title ?></h1>
    </div>
    <div class="d-flex flex-row-reverse">
        <?php
        $form->prepare();

        echo $this->form()->openTag($this->form);
        echo $this->formRow($form->get('sort-by'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<?= $this->partial('partials/grid', ['games' => $games]) ?>
