<style>
    ul {
        color: red;
    }
</style>

<?php
/**
 * @var \Laminas\Form\Form $form
 * @var \Laminas\Mvc\Plugin\FlashMessenger\View\Helper\FlashMessenger $flashMessenger
 */

use Laminas\Mvc\Plugin\FlashMessenger\FlashMessenger;

$flashMessenger = $this->flashMessenger();
?>

<?= $flashMessenger->render(FlashMessenger::NAMESPACE_ERROR, ['alert', 'alert-danger', 'list-unstyled', 'text-center']) ?>

<h1>Register</h1>

<?php $form->prepare() ?>
<?= $this->form()->openTag($this->form) ?>

<div class="form-group">
    <?= $this->formRow($form->get('username')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('email')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('password')) ?>
</div>

<?= $this->formRow($form->get('submit')) ?>

<?= $this->form()->closeTag() ?>


