<h1>Categories</h1>

<div class="row">
    <div class="col">
        <h2><a href="<?= $this->url('categories/action') ?>">Action</a></h2>
        <h2><a href="<?= $this->url('categories/action-role-playing-game') ?>">Action RPG</a></h2>
        <h2><a href="<?= $this->url('categories/anime') ?>">Anime</a></h2>
        <h2><a href="<?= $this->url('categories/battle-royale') ?>">Battle Royale</a></h2>
        <h2><a href="<?= $this->url('categories/card') ?>">Card</a></h2>
        <h2><a href="<?= $this->url('categories/fighting') ?>">Fighting</a></h2>
        <h2><a href="<?= $this->url('categories/first-person') ?>">First Person</a></h2>
        <h2><a href="<?= $this->url('categories/flight') ?>">Flight</a></h2>
        <h2><a href="<?= $this->url('categories/horror') ?>">Horror</a></h2>
        <h2><a href="<?= $this->url('categories/low-specifications') ?>">Low Specs</a></h2>
        <h2><a href="<?= $this->url('categories/martial-arts') ?>">Martial Arts</a></h2>
        <h2><a href="<?= $this->url('categories/mmo') ?>">MMO</a></h2>
        <h2><a href="<?= $this->url('categories/mmofps') ?>">MMO-FPS</a></h2>
        <h2><a href="<?= $this->url('categories/mmorts') ?>">MMO-RTS</a></h2>
        <h2><a href="<?= $this->url('categories/mmorpg') ?>">MMO-RPG</a></h2>
        <h2><a href="<?= $this->url('categories/mmotps') ?>">MMO-TPS</a></h2>
        <h2><a href="<?= $this->url('categories/military') ?>">Military</a></h2>
        <h2><a href="<?= $this->url('categories/multiplayer-online-battle-arena') ?>">Online Battle Arena</a></h2>
        <h2><a href="<?= $this->url('categories/open-world') ?>">Open World</a></h2>
        <h2><a href="<?= $this->url('categories/permadeath') ?>">Permadeath</a></h2>
        <h2><a href="<?= $this->url('categories/pixel') ?>">Pixel</a></h2>
        <h2><a href="<?= $this->url('categories/pve') ?>">PVE</a></h2>
        <h2><a href="<?= $this->url('categories/pvp') ?>">PVP</a></h2>
        <h2><a href="<?= $this->url('categories/racing') ?>">Racing</a></h2>
        <h2><a href="<?= $this->url('categories/sailing') ?>">Sailing</a></h2>
        <h2><a href="<?= $this->url('categories/sandbox') ?>">Sandbox</a></h2>
        <h2><a href="<?= $this->url('categories/science-fiction') ?>">Sci-Fi</a></h2>
        <h2><a href="<?= $this->url('categories/shooter') ?>">Shooter</a></h2>
        <h2><a href="<?= $this->url('categories/side-scroller') ?>">Side Scroller</a></h2>
        <h2><a href="<?= $this->url('categories/social') ?>">Social</a></h2>
        <h2><a href="<?= $this->url('categories/space') ?>">Space</a></h2>
        <h2><a href="<?= $this->url('categories/sports') ?>">Sports</a></h2>
        <h2><a href="<?= $this->url('categories/strategy') ?>">Strategy</a></h2>
        <h2><a href="<?= $this->url('categories/superhero') ?>">Superhero</a></h2>
        <h2><a href="<?= $this->url('categories/survival') ?>">Survival</a></h2>
        <h2><a href="<?= $this->url('categories/tank') ?>">Tank</a></h2>
        <h2><a href="<?= $this->url('categories/third-person') ?>">Third Person</a></h2>
        <h2><a href="<?= $this->url('categories/top-down') ?>">Top Down</a></h2>
        <h2><a href="<?= $this->url('categories/tower-defense') ?>">Tower Defense</a></h2>
        <h2><a href="<?= $this->url('categories/turn-based') ?>">Turn Based</a></h2>
        <h2><a href="<?= $this->url('categories/two-dimension') ?>">2D</a></h2>
        <h2><a href="<?= $this->url('categories/voxel') ?>">Voxel</a></h2>
        <h2><a href="<?= $this->url('categories/zombie') ?>">Zombie</a></h2>
    </div>
</div>
