<h1>Categories</h1>

<div class="row">
    <div class="col">
        <h2><a href="<?= $this->url('categories/action') ?>">Action</a></h2>
        <h2><a href="<?= $this->url('categories/action-role-playing-game') ?>">Action RPG</a></h2>
        <h2><a href="<?= $this->url('categories/anime') ?>">Anime</a></h2>
        <h2><a href="<?= $this->url('categories/battle-royale') ?>">Battle Royale</a></h2>
        <h2><a href="<?= $this->url('categories/card') ?>">Card</a></h2>
        <h2><a href="<?= $this->url('categories/fighting') ?>">Fighting</a></h2>
        <h2><a href="<?= $this->url('categories/first-person') ?>">First Person</a></h2>
        <h2><a href="<?= $this->url('categories/flight') ?>">Flight</a></h2>
        <h2><a href="<?= $this->url('categories/horror') ?>">Horror</a></h2>
        <h2><a href="<?= $this->url('categories/low-specifications') ?>">Low Specs</a></h2>
        <h2><a href="<?= $this->url('categories/martial-arts') ?>">Martial Arts</a></h2>
    </div>
</div>
