<h1 class="mb-4">Categories</h1>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'action']) ?>">Action</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'action-role-playing-game']) ?>">Action RPG</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'anime']) ?>">Anime</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'battle-royale']) ?>">Battle Royale</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'card']) ?>">Card</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'fighting']) ?>">Fighting</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'first-person']) ?>">First Person</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'flight']) ?>">Flight</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'horror']) ?>">Horror</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'low-specifications']) ?>">Low Specs</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'martial-arts']) ?>">Martial Arts</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'mmo']) ?>">MMO</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'mmofps']) ?>">MMO-FPS</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'mmorts']) ?>">MMO-RTS</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'mmorpg']) ?>">MMO-RPG</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'mmotps']) ?>">MMO-TPS</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'military']) ?>">Military</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'multiplayer-online-battle-arena']) ?>">Online Battle Arena</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'open-world']) ?>">Open World</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'permadeath']) ?>">Permadeath</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'pixel']) ?>">Pixel</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'pve']) ?>">PVE</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'pvp']) ?>">PVP</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'racing']) ?>">Racing</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'sailing']) ?>">Sailing</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'sandbox']) ?>">Sandbox</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'science-fiction']) ?>">Sci-Fi</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'shooter']) ?>">Shooter</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'side-scroller']) ?>">Side Scroller</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'social']) ?>">Social</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'space']) ?>">Space</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'sports']) ?>">Sports</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'strategy']) ?>">Strategy</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'superhero']) ?>">Superhero</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'survival']) ?>">Survival</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'tank']) ?>">Tank</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'third-person']) ?>">Third Person</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'top-down']) ?>">Top Down</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'tower-defense']) ?>">Tower Defense</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'turn-based']) ?>">Turn Based</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'two-dimension']) ?>">2D</a></h2>
    </div>
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'voxel']) ?>">Voxel</a></h2>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-4 themed-grid-col shadow-sm">
        <h2><a href="<?= $this->url('category', ['category' => 'zombie']) ?>">Zombie</a></h2>
    </div>
</div>
