<?php

$this->headTitle('Account Overview');

?>

<h1>Account Overview</h1>

<table class="table mt-5">
    <tbody>
        <tr>
            <td>Username</td>
            <td><?= $this->user->getUsername() ?></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><?= $this->user->getEmail() ?></td>
        </tr>
    </tbody>
</table>

<a href="<?= $this->url('account-delete', ['userId' => $this->user->getId()]) ?>"  class="btn btn-danger">Delete account</a>