<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('FreeToLame')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('js/virtual-select/virtual-select.min.css'))
            ->prependStylesheet($this->basePath('js/virtual-select/tooltip.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>

        <?php $this->navigation('navigation')->menu()->setPartial('application/navigation/nav.phtml') ?>
        <?= $this->navigation('navigation')->menu()->render() ?>

        <div class="container mt-3">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>Content provided by <a href="https://www.freetogame.com/api-doc">FreeToGame</a>.
            </footer>
        </div>

        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
            ->prependFile($this->basePath('js/virtual-select/virtual-select.min.js'))
            ->prependFile($this->basePath('js/virtual-select/tooltip.min.js'))
        ?>
    </body>
    <script>
        VirtualSelect.init({
            ele: '#search-form',
            multiple: true,
            name: 'search-terms',
            placeholder: 'Search',
            showSelectedOptionsFirst: true,
            options: [
                { label: 'Action', value: 'action' },
                { label: 'Action RPG', value: 'action-rpg' },
                { label: 'Anime', value: 'anime' },
                { label: 'Battle Royal', value: 'battle-royale' },
                { label: 'Card', value: 'card' },
                { label: 'Fantasy', value: 'fantasy' },
                { label: 'Fighting', value: 'fighting' },
                { label: 'First Person', value: 'first-person' },
                { label: 'Flying', value: 'flight' },
                { label: 'Horror', value: 'horror' },
                { label: 'Low Specs', value: 'low-specs' },
                { label: 'Martial Arts', value: 'martial-arts' },
                { label: 'MMO', value: 'mmo' },
                { label: 'MMO-FPS', value: 'mmofps' },
                { label: 'MMO-RTS', value: 'mmorts' },
                { label: 'MMO-RPG', value: 'mmorpg' },
                { label: 'MMO-TPS', value: 'mmotps' },
                { label: 'Military', value: 'military' },
                { label: 'Multiplayer Online Battle', value: 'multiplayer-online-battle-arena' },
                { label: 'Open World', value: 'open-world' },
                { label: 'Permadeath', value: 'permadeath' },
                { label: 'Pixel', value: 'pixel' },
                { label: 'PVE', value: 'pve' },
                { label: 'PVP', value: 'pvp' },
                { label: 'Racing', value: 'racing' },
                { label: 'Sailing', value: 'sailing' },
                { label: 'Sandbox', value: 'sandbox' },
                { label: 'Sci-Fi', value: 'sci-fi' },
                { label: 'Shooter', value: 'shooter' },
                { label: 'Side Scroller', value: 'side-scroller' },
                { label: 'Social', value: 'social' },
                { label: 'Space', value: 'space' },
                { label: 'Sports', value: 'sports' },
                { label: 'Strategy', value: 'strategy' },
                { label: 'Superhero', value: 'superhero' },
                { label: 'Survival', value: 'survival' },
                { label: 'Tank', value: 'tank' },
                { label: 'Third Person', value: 'third-person' },
                { label: '3D', value: '3D' },
                { label: 'Top Down', value: 'top-down' },
                { label: 'Tower Defense', value: 'tower-defense' },
                { label: 'Turn Based', value: 'turn-based' },
                { label: '2D', value: '2D' },
                { label: 'Voxel', value: 'voxel' },
                { label: 'Zombie', value: 'zombie' },
            ],
        });
    </script>
</html>
