<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('FreeToLame')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('js/lib/virtual-select/virtual-select.min.css'))
            ->prependStylesheet($this->basePath('js/lib/virtual-select/tooltip.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/lib/bootstrap.min.js'))
            ->prependFile($this->basePath('js/lib/jquery-3.5.1.min.js'))
            ->prependFile($this->basePath('js/lib/virtual-select/virtual-select.min.js'))
            ->prependFile($this->basePath('js/lib/virtual-select/tooltip.min.js'))
        ?>
    </head>
    <body>

        <?php $this->navigation('navigation')->menu()->setPartial('application/navigation/nav.phtml') ?>
        <?= $this->navigation('navigation')->menu()->render() ?>

        <div class="container mt-3">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>Content provided by <a href="https://www.freetogame.com/api-doc">FreeToGame</a>.
            </footer>
        </div>

        <?= $this->inlineScript()
                ->prependFile($this->basePath('js/search-bar.js'))
        ?>
    </body>
</html>
