<div class="row">
    <div class="col">
        <img src="<?= $this->escapeHtml($this->game['thumbnail']) ?>" class="img-fluid rounded">

        <form method="GET" action="<?= $this->escapeHtml($this->game['game_url']) ?>">
            <input type="submit" class="btn btn-primary" value="Play now!">
        </form>
    </div>
    <div class="col">
        <h1><?= $this->escapeHtml($this->game['title']) ?></h1>
        <p><?= $this->escapeHtml($this->game['description']) ?></p>
    </div>
</div>

<?php if($this->game['screenshots']): ?>
    <?php $count = 0 ?>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <?php foreach ($this->game['screenshots'] as $screenshot): ?>
                <li data-target="#carouselExampleIndicators" data-slide-to="<?= $count ?>" <?= $count === 0 ? 'class="active"' : '' ?>></li>
                <?php $count++ ?>
            <?php endforeach; ?>
        </ol>
        <div class="carousel-inner">
            <?php $count = 0 ?>
            <?php foreach ($this->game['screenshots'] as $screenshot): ?>
                <div class="carousel-item <?= $count === 0 ? 'active': '' ?>">
                    <img src="<?= $this->game['screenshots'][$count]['image'] ?>" class="d-block w-100">
                </div>
                <?php $count++ ?>
            <?php endforeach; ?>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<?php endif; ?>

<h2>Details</h2>

<table class="table">
    <tbody>
        <tr>
            <td>Genre</td>
            <td><?= $this->escapeHtml($this->game['genre']) ?></td>
        </tr>
        <tr>
            <td>Platform</td>
            <td><?= $this->escapeHtml($this->game['platform']) ?></td>
        </tr>
        <tr>
            <td>Publisher</td>
            <td><?= $this->escapeHtml($this->game['publisher']) ?></td>
        </tr>
        <tr>
            <td>Developer</td>
            <td><?= $this->escapeHtml($this->game['developer']) ?></td>
        </tr>
        <tr>
            <td>Release Date</td>
            <td><?= $this->escapeHtml($this->game['release_date']) ?></td>
        </tr>
    </tbody>
</table>

<?php if ($this->hasSystemRequirements):?>
    <h2>System requirements</h2>
    <table class="table">
        <tbody>
            <tr>
                <td>Operating System</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['os']) ?></td>
            </tr>
            <tr>
                <td>Processor</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['processor']) ?></td>
            </tr>
            <tr>
                <td>Memory</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['memory']) ?></td>
            </tr>
            <tr>
                <td>Graphics</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['graphics']) ?></td>
            </tr>
            <tr>
                <td>Storage</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['storage']) ?></td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>
