<div class="d-flex flex-column flex-lg-row">
    <div class="d-flex flex-grow-1 align-self-center flex-column">
        <img src="<?= $this->escapeHtml($this->game['thumbnail']) ?>" class="rounded mx-auto img-thumbnail">
        <form method="GET" action="<?= $this->escapeHtml($this->game['game_url']) ?>" class="mx-auto mt-3">
            <input type="submit" class="btn btn-primary py-2 px-4" value="Play now!">
        </form>
    </div>
    <div class="w-50">
        <div class="d-flex align-items-end">
            <h1>
                <?= $this->escapeHtml($this->game['title']) ?>
            </h1>
        </div>

        <p class="small text-muted">
            <?= $this->escapeHtml($this->game['genre']) ?> ·
            <?= $this->escapeHtml($this->game['platform']) ?> ·
            <?= $this->escapeHtml($this->game['publisher']) ?> ·
            <?= $this->escapeHtml($this->game['developer']) ?> ·
            <?= $this->escapeHtml($this->game['release_date']) ?>
        </p>
        <p><?= $this->escapeHtml($this->game['description']) ?></p>
    </div>
</div>

<?php if($this->game['screenshots']): ?>
    <?php $count = 0 ?>
    <div id="carouselExampleIndicators" class="carousel slide mt-5" data-ride="carousel">
        <ol class="carousel-indicators">
            <?php foreach ($this->game['screenshots'] as $screenshot): ?>
                <li data-target="#carouselExampleIndicators" data-slide-to="<?= $count ?>" <?= $count === 0 ? 'class="active"' : '' ?>></li>
                <?php $count++ ?>
            <?php endforeach; ?>
        </ol>
        <div class="carousel-inner">
            <?php $count = 0 ?>
            <?php foreach ($this->game['screenshots'] as $screenshot): ?>
                <div class="carousel-item <?= $count === 0 ? 'active': '' ?>">
                    <img src="<?= $this->game['screenshots'][$count]['image'] ?>" class="d-block w-100">
                </div>
                <?php $count++ ?>
            <?php endforeach; ?>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<?php endif; ?>

<?php if ($this->hasSystemRequirements):?>
    <div class="mt-5">
        <h2>System requirements</h2>

        <table class="table">
            <tbody>
            <tr>
                <td>Operating System</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['os']) ?></td>
            </tr>
            <tr>
                <td>Processor</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['processor']) ?></td>
            </tr>
            <tr>
                <td>Memory</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['memory']) ?></td>
            </tr>
            <tr>
                <td>Graphics</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['graphics']) ?></td>
            </tr>
            <tr>
                <td>Storage</td>
                <td><?= $this->escapeHtml($this->game['minimum_system_requirements']['storage']) ?></td>
            </tr>
            </tbody>
        </table>
    </div>
<?php endif; ?>
