<nav class="navbar navbar-expand-sm navbar-dark bg-dark" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="<?= $this->url('home') ?>">FreeToPlay</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="<?= $this->url('categories') ?>" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="<?= $this->url('categories') ?>">See all</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'action']) ?>">Action</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'action-role-playing-game']) ?>">Action RPG</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'anime']) ?>">Anime</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'battle-royale']) ?>">Battle Royale</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'card']) ?>">Card</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'fighting']) ?>">Fighting</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'first-person']) ?>">First Person</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'flight']) ?>">Flight</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'horror']) ?>">Horror</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'low-specifications']) ?>">Low Specs</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'martial-arts']) ?>">Martial Arts</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'mmo']) ?>">MMO</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'mmofps']) ?>">MMO-FPS</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'mmorts']) ?>">MMO-RTS</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'mmorpg']) ?>">MMO-RPG</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'mmotps']) ?>">MMO-TPS</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'military']) ?>">Military</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'multiplayer-online-battle-arena']) ?>">Online Battle Arena</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'open-world']) ?>">Open World</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'permadeath']) ?>">Permadeath</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'pixel']) ?>">Pixel</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'pve']) ?>">PVE</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'pvp']) ?>">PVP</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'racing']) ?>">Racing</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'sailing']) ?>">Sailing</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'sandbox']) ?>">Sandbox</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'science-fiction']) ?>">Sci-Fi</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'shooter']) ?>">Shooter</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'side-scroller']) ?>">Side Scroller</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'social']) ?>">Social</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'space']) ?>">Space</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'sports']) ?>">Sports</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'strategy']) ?>">Strategy</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'superhero']) ?>">Superhero</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'survival']) ?>">Survival</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'tank']) ?>">Tank</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'third-person']) ?>">Third Person</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'top-down']) ?>">Top Down</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'tower-defense']) ?>">Tower Defense</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'turn-based']) ?>">Turn Based</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'two-dimension']) ?>">2D</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'voxel']) ?>">Voxel</a>
                        <a class="dropdown-item" href="<?= $this->url('category', ['category' => 'zombie']) ?>">Zombie</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="<?= $this->url('platforms') ?>" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Platforms
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="<?= $this->url('platforms') ?>">See all</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?= $this->url('platforms/browser') ?>">Browser</a>
                        <a class="dropdown-item" href="<?= $this->url('platforms/pc') ?>">PC</a>
                    </div>
                </li>
                <?php

                /** @var \User\View\Helper\AuthenticationHelper $auth */
                $auth = $this->authentication();

                if ($auth->hasIdentity()): ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('account', ['userId' => $auth->getAuthenticatedUserId()]) ?>">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('logout') ?>">Logout</a>
                    </li>
                <?php else: ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('register') ?>">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('login') ?>">Login</a>
                    </li>
                <?php endif; ?>
            </ul>
            <form action="<?= $this->url('search-results') ?>" method="post" class="form-inline">
                <div id="search-form" class="mr-2" style="width: 250px"></div>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
