<div class="row justify-content-between align-items-center pb-3">
    <div class="col-4">
        <h1>PC games</h1>
    </div>
    <div class="col-4">
        <?php
        $this->form->prepare();

        echo $this->form()->openTag($this->form);
        echo $this->formRow($this->form->get('sort-by'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<div class="row">
    <?php $count = 0 ?>
    <?php foreach ($this->games as $game): ?>
        <?= $this->partial('partials/game-card', ['game' => $game]) ?>
        <?php $count++ ?>
        <?php if ($count > 2): ?>
            <?php $count = 0 ?>
            <div class="w-100"></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

